import type { Locale } from "@/lib/brcode/labels";

/** HIBP /dataclasses names → pt-BR labels. Unknown values fall back to English. */
const DATA_CLASS_LABELS_PT: Record<string, string> = {
  "Academic records": "Registros acadêmicos",
  "Account balances": "Saldos de conta",
  "Address book contacts": "Contatos da agenda",
  "Age groups": "Faixas etárias",
  Ages: "Idades",
  "AI prompts": "Prompts de IA",
  Appointments: "Compromissos",
  "Apps installed on devices": "Apps instalados em dispositivos",
  "Astrological signs": "Signos astrológicos",
  "Audio recordings": "Gravações de áudio",
  "Auth tokens": "Tokens de autenticação",
  Avatars: "Avatares",
  "Bank account numbers": "Números de conta bancária",
  "Beauty ratings": "Avaliações de aparência",
  "Biometric data": "Dados biométricos",
  Bios: "Biografias",
  "Browser user agent details": "Detalhes de user agent do navegador",
  "Browsing histories": "Históricos de navegação",
  "Buying preferences": "Preferências de compra",
  "Car ownership statuses": "Status de posse de veículo",
  "Career levels": "Níveis de carreira",
  "Cellular network names": "Nomes de rede celular",
  "Charitable donations": "Doações a instituições",
  "Chat logs": "Registros de chat",
  "Citizenship statuses": "Status de cidadania",
  "Clothing sizes": "Tamanhos de roupa",
  Comments: "Comentários",
  "Company names": "Nomes de empresas",
  "Credit card CVV": "CVV de cartão de crédito",
  "Credit cards": "Cartões de crédito",
  "Credit scores": "Scores de crédito",
  "Credit status information": "Informações de status de crédito",
  "Cryptocurrency wallet addresses": "Endereços de carteira de criptomoeda",
  "Customer feedback": "Feedback de clientes",
  "Customer interactions": "Interações com clientes",
  "Customer service comments": "Comentários de atendimento",
  "Dates of birth": "Datas de nascimento",
  "Deceased date": "Data de falecimento",
  "Deceased statuses": "Status de falecimento",
  "Delivery instructions": "Instruções de entrega",
  "Device information": "Informações do dispositivo",
  "Device serial numbers": "Números de série de dispositivos",
  "Device usage tracking data": "Dados de rastreamento de uso do dispositivo",
  Disabilities: "Deficiências",
  "Display names": "Nomes de exibição",
  "Drinking habits": "Hábitos de consumo de álcool",
  "Driver's licenses": "Carteiras de motorista",
  "Drug habits": "Hábitos de uso de drogas",
  Earnings: "Rendimentos",
  "Eating habits": "Hábitos alimentares",
  "Education levels": "Níveis de escolaridade",
  "Email addresses": "Endereços de e-mail",
  "Email messages": "Mensagens de e-mail",
  Employers: "Empregadores",
  "Employment statuses": "Status de emprego",
  "Encrypted keys": "Chaves criptografadas",
  Ethnicities: "Etnias",
  "Family members' names": "Nomes de familiares",
  "Family plans": "Planos familiares",
  "Family structure": "Estrutura familiar",
  "Financial investments": "Investimentos financeiros",
  "Financial transactions": "Transações financeiras",
  "Fitness levels": "Níveis de condicionamento físico",
  "Flights taken": "Voos realizados",
  "Forum posts": "Postagens em fóruns",
  Genders: "Gêneros",
  "Geographic locations": "Localizações geográficas",
  "Government issued IDs": "Documentos emitidos pelo governo",
  "Health insurance information": "Informações de plano de saúde",
  "Historical passwords": "Senhas antigas",
  "HIV statuses": "Status de HIV",
  "Home ownership statuses": "Status de posse de imóvel",
  "Homepage URLs": "URLs de página inicial",
  "IMEI numbers": "Números IMEI",
  "IMSI numbers": "Números IMSI",
  "Income levels": "Níveis de renda",
  "Instant messenger identities": "Identidades de mensageiros instantâneos",
  "IP addresses": "Endereços IP",
  "IQ levels": "Níveis de QI",
  "Job applications": "Candidaturas a emprego",
  "Job titles": "Cargos",
  "Language preferences": "Preferências de idioma",
  "Latitude and longitude pairs": "Pares de latitude e longitude",
  "Licence plates": "Placas de veículo",
  "Living costs": "Custos de vida",
  "Loan information": "Informações de empréstimo",
  "Login histories": "Históricos de login",
  "Loyalty program details": "Detalhes de programa de fidelidade",
  "MAC addresses": "Endereços MAC",
  "Marital statuses": "Estados civis",
  "Military service": "Serviço militar",
  "Mnemonic phrases": "Frases mnemônicas",
  "Mothers maiden names": "Nomes de solteira das mães",
  Names: "Nomes",
  Nationalities: "Nacionalidades",
  "Net worths": "Patrimônios líquidos",
  Nicknames: "Apelidos",
  Occupations: "Ocupações",
  "Parenting plans": "Planos de parentalidade",
  "Partial credit card data": "Dados parciais de cartão de crédito",
  "Partial dates of birth": "Datas de nascimento parciais",
  "Partial government issued IDs": "Documentos governamentais parciais",
  "Partial phone numbers": "Números de telefone parciais",
  "Passport numbers": "Números de passaporte",
  "Password hints": "Dicas de senha",
  "Password strengths": "Força de senha",
  Passwords: "Senhas",
  "Payment histories": "Históricos de pagamento",
  "Payment methods": "Métodos de pagamento",
  "Personal descriptions": "Descrições pessoais",
  "Personal health data": "Dados pessoais de saúde",
  "Personal interests": "Interesses pessoais",
  "Phone numbers": "Números de telefone",
  Photos: "Fotos",
  "Physical addresses": "Endereços físicos",
  "Physical attributes": "Atributos físicos",
  PINs: "PINs",
  "Places of birth": "Locais de nascimento",
  "Political donations": "Doações políticas",
  "Political views": "Opiniões políticas",
  "Private messages": "Mensagens privadas",
  "Professional skills": "Habilidades profissionais",
  "Profile photos": "Fotos de perfil",
  "Profile statistics": "Estatísticas de perfil",
  Purchases: "Compras",
  "Purchasing habits": "Hábitos de compra",
  Races: "Raças",
  "Recovery email addresses": "E-mails de recuperação",
  "Relationship statuses": "Status de relacionamento",
  Religions: "Religiões",
  "Reward program balances": "Saldos de programas de recompensa",
  Salutations: "Saudações",
  "School grades (class levels)": "Séries escolares",
  "Security questions and answers": "Perguntas e respostas de segurança",
  "Sexual fetishes": "Fetiches sexuais",
  "Sexual orientations": "Orientações sexuais",
  "Shipment tracking numbers": "Números de rastreamento de envio",
  "Smoking habits": "Hábitos de fumo",
  "SMS messages": "Mensagens SMS",
  "Social connections": "Conexões sociais",
  "Social media profiles": "Perfis de redes sociais",
  "Social security numbers": "Números de previdência social",
  "Socioeconomic levels": "Níveis socioeconômicos",
  "Spoken languages": "Idiomas falados",
  "Spouses names": "Nomes de cônjuges",
  "Support tickets": "Chamados de suporte",
  "Survey results": "Resultados de pesquisas",
  "Tattoo status": "Status de tatuagem",
  "Taxation records": "Registros fiscais",
  "Telecommunications carrier": "Operadora de telecomunicações",
  "Time zones": "Fusos horários",
  "Travel habits": "Hábitos de viagem",
  "Travel plans": "Planos de viagem",
  "User statuses": "Status de usuário",
  "User website URLs": "URLs de sites de usuários",
  Usernames: "Nomes de usuário",
  "Utility bills": "Contas de serviços públicos",
  "Vehicle details": "Detalhes de veículos",
  "Vehicle identification numbers (VINs)": "Números de identificação de veículos (VIN)",
  "Vehicle registration plates": "Placas de registro de veículos",
  "VIP statuses": "Status VIP",
  "Warranty claims": "Solicitações de garantia",
  "Website activity": "Atividade em sites",
  "Work habits": "Hábitos de trabalho",
  "Years of professional experience": "Anos de experiência profissional",
};

export function translateDataClass(name: string, locale: Locale): string {
  if (locale !== "pt") return name;
  return DATA_CLASS_LABELS_PT[name] ?? name;
}

export function translateDataClasses(names: string[], locale: Locale): string[] {
  return names.map((name) => translateDataClass(name, locale));
}
