// ISO 4217 numeric → alpha-3 codes and English names (SIX Group list via currency-codes@2.2.0, 2024-06-25).
// Reference data only; localized labels live in currency-labels.ts.

export const ISO4217_NUMERIC_TO_ALPHA: Readonly<Record<string, string>> = {
  "104": "MMK",
  "108": "BIF",
  "116": "KHR",
  "124": "CAD",
  "132": "CVE",
  "136": "KYD",
  "144": "LKR",
  "152": "CLP",
  "156": "CNY",
  "170": "COP",
  "174": "KMF",
  "188": "CRC",
  "192": "CUP",
  "203": "CZK",
  "208": "DKK",
  "214": "DOP",
  "222": "SVC",
  "230": "ETB",
  "232": "ERN",
  "238": "FKP",
  "242": "FJD",
  "262": "DJF",
  "270": "GMD",
  "292": "GIP",
  "320": "GTQ",
  "324": "GNF",
  "328": "GYD",
  "332": "HTG",
  "340": "HNL",
  "344": "HKD",
  "348": "HUF",
  "352": "ISK",
  "356": "INR",
  "360": "IDR",
  "364": "IRR",
  "368": "IQD",
  "376": "ILS",
  "388": "JMD",
  "392": "JPY",
  "398": "KZT",
  "400": "JOD",
  "404": "KES",
  "408": "KPW",
  "410": "KRW",
  "414": "KWD",
  "417": "KGS",
  "418": "LAK",
  "422": "LBP",
  "426": "LSL",
  "430": "LRD",
  "434": "LYD",
  "446": "MOP",
  "454": "MWK",
  "458": "MYR",
  "462": "MVR",
  "480": "MUR",
  "484": "MXN",
  "496": "MNT",
  "498": "MDL",
  "504": "MAD",
  "512": "OMR",
  "516": "NAD",
  "524": "NPR",
  "532": "ANG",
  "533": "AWG",
  "548": "VUV",
  "554": "NZD",
  "558": "NIO",
  "566": "NGN",
  "578": "NOK",
  "586": "PKR",
  "590": "PAB",
  "598": "PGK",
  "600": "PYG",
  "604": "PEN",
  "608": "PHP",
  "634": "QAR",
  "643": "RUB",
  "646": "RWF",
  "654": "SHP",
  "682": "SAR",
  "690": "SCR",
  "702": "SGD",
  "704": "VND",
  "706": "SOS",
  "710": "ZAR",
  "728": "SSP",
  "748": "SZL",
  "752": "SEK",
  "756": "CHF",
  "760": "SYP",
  "764": "THB",
  "776": "TOP",
  "780": "TTD",
  "784": "AED",
  "788": "TND",
  "800": "UGX",
  "807": "MKD",
  "818": "EGP",
  "826": "GBP",
  "834": "TZS",
  "840": "USD",
  "858": "UYU",
  "860": "UZS",
  "882": "WST",
  "886": "YER",
  "901": "TWD",
  "924": "ZWG",
  "925": "SLE",
  "926": "VED",
  "927": "UYW",
  "928": "VES",
  "929": "MRU",
  "930": "STN",
  "931": "CUC",
  "933": "BYN",
  "934": "TMT",
  "936": "GHS",
  "938": "SDG",
  "940": "UYI",
  "941": "RSD",
  "943": "MZN",
  "944": "AZN",
  "946": "RON",
  "947": "CHE",
  "948": "CHW",
  "949": "TRY",
  "950": "XAF",
  "951": "XCD",
  "952": "XOF",
  "953": "XPF",
  "955": "XBA",
  "956": "XBB",
  "957": "XBC",
  "958": "XBD",
  "959": "XAU",
  "960": "XDR",
  "961": "XAG",
  "962": "XPT",
  "963": "XTS",
  "964": "XPD",
  "965": "XUA",
  "967": "ZMW",
  "968": "SRD",
  "969": "MGA",
  "970": "COU",
  "971": "AFN",
  "972": "TJS",
  "973": "AOA",
  "975": "BGN",
  "976": "CDF",
  "977": "BAM",
  "978": "EUR",
  "979": "MXV",
  "980": "UAH",
  "981": "GEL",
  "984": "BOV",
  "985": "PLN",
  "986": "BRL",
  "990": "CLF",
  "994": "XSU",
  "997": "USN",
  "999": "XXX",
  "008": "ALL",
  "051": "AMD",
  "032": "ARS",
  "036": "AUD",
  "052": "BBD",
  "050": "BDT",
  "048": "BHD",
  "060": "BMD",
  "096": "BND",
  "068": "BOB",
  "044": "BSD",
  "064": "BTN",
  "072": "BWP",
  "084": "BZD",
  "012": "DZD",
  "090": "SBD"
};

export const ISO4217_ENGLISH_NAMES: Readonly<Record<string, string>> = {
  "AED": "UAE Dirham",
  "AFN": "Afghani",
  "ALL": "Lek",
  "AMD": "Armenian Dram",
  "ANG": "Netherlands Antillean Guilder",
  "AOA": "Kwanza",
  "ARS": "Argentine Peso",
  "AUD": "Australian Dollar",
  "AWG": "Aruban Florin",
  "AZN": "Azerbaijan Manat",
  "BAM": "Convertible Mark",
  "BBD": "Barbados Dollar",
  "BDT": "Taka",
  "BGN": "Bulgarian Lev",
  "BHD": "Bahraini Dinar",
  "BIF": "Burundi Franc",
  "BMD": "Bermudian Dollar",
  "BND": "Brunei Dollar",
  "BOB": "Boliviano",
  "BOV": "Mvdol",
  "BRL": "Brazilian Real",
  "BSD": "Bahamian Dollar",
  "BTN": "Ngultrum",
  "BWP": "Pula",
  "BYN": "Belarusian Ruble",
  "BZD": "Belize Dollar",
  "CAD": "Canadian Dollar",
  "CDF": "Congolese Franc",
  "CHE": "WIR Euro",
  "CHF": "Swiss Franc",
  "CHW": "WIR Franc",
  "CLF": "Unidad de Fomento",
  "CLP": "Chilean Peso",
  "CNY": "Yuan Renminbi",
  "COP": "Colombian Peso",
  "COU": "Unidad de Valor Real",
  "CRC": "Costa Rican Colon",
  "CUC": "Peso Convertible",
  "CUP": "Cuban Peso",
  "CVE": "Cabo Verde Escudo",
  "CZK": "Czech Koruna",
  "DJF": "Djibouti Franc",
  "DKK": "Danish Krone",
  "DOP": "Dominican Peso",
  "DZD": "Algerian Dinar",
  "EGP": "Egyptian Pound",
  "ERN": "Nakfa",
  "ETB": "Ethiopian Birr",
  "EUR": "Euro",
  "FJD": "Fiji Dollar",
  "FKP": "Falkland Islands Pound",
  "GBP": "Pound Sterling",
  "GEL": "Lari",
  "GHS": "Ghana Cedi",
  "GIP": "Gibraltar Pound",
  "GMD": "Dalasi",
  "GNF": "Guinean Franc",
  "GTQ": "Quetzal",
  "GYD": "Guyana Dollar",
  "HKD": "Hong Kong Dollar",
  "HNL": "Lempira",
  "HTG": "Gourde",
  "HUF": "Forint",
  "IDR": "Rupiah",
  "ILS": "New Israeli Sheqel",
  "INR": "Indian Rupee",
  "IQD": "Iraqi Dinar",
  "IRR": "Iranian Rial",
  "ISK": "Iceland Krona",
  "JMD": "Jamaican Dollar",
  "JOD": "Jordanian Dinar",
  "JPY": "Yen",
  "KES": "Kenyan Shilling",
  "KGS": "Som",
  "KHR": "Riel",
  "KMF": "Comorian Franc ",
  "KPW": "North Korean Won",
  "KRW": "Won",
  "KWD": "Kuwaiti Dinar",
  "KYD": "Cayman Islands Dollar",
  "KZT": "Tenge",
  "LAK": "Lao Kip",
  "LBP": "Lebanese Pound",
  "LKR": "Sri Lanka Rupee",
  "LRD": "Liberian Dollar",
  "LSL": "Loti",
  "LYD": "Libyan Dinar",
  "MAD": "Moroccan Dirham",
  "MDL": "Moldovan Leu",
  "MGA": "Malagasy Ariary",
  "MKD": "Denar",
  "MMK": "Kyat",
  "MNT": "Tugrik",
  "MOP": "Pataca",
  "MRU": "Ouguiya",
  "MUR": "Mauritius Rupee",
  "MVR": "Rufiyaa",
  "MWK": "Malawi Kwacha",
  "MXN": "Mexican Peso",
  "MXV": "Mexican Unidad de Inversion (UDI)",
  "MYR": "Malaysian Ringgit",
  "MZN": "Mozambique Metical",
  "NAD": "Namibia Dollar",
  "NGN": "Naira",
  "NIO": "Cordoba Oro",
  "NOK": "Norwegian Krone",
  "NPR": "Nepalese Rupee",
  "NZD": "New Zealand Dollar",
  "OMR": "Rial Omani",
  "PAB": "Balboa",
  "PEN": "Sol",
  "PGK": "Kina",
  "PHP": "Philippine Peso",
  "PKR": "Pakistan Rupee",
  "PLN": "Zloty",
  "PYG": "Guarani",
  "QAR": "Qatari Rial",
  "RON": "Romanian Leu",
  "RSD": "Serbian Dinar",
  "RUB": "Russian Ruble",
  "RWF": "Rwanda Franc",
  "SAR": "Saudi Riyal",
  "SBD": "Solomon Islands Dollar",
  "SCR": "Seychelles Rupee",
  "SDG": "Sudanese Pound",
  "SEK": "Swedish Krona",
  "SGD": "Singapore Dollar",
  "SHP": "Saint Helena Pound",
  "SLE": "Leone",
  "SOS": "Somali Shilling",
  "SRD": "Surinam Dollar",
  "SSP": "South Sudanese Pound",
  "STN": "Dobra",
  "SVC": "El Salvador Colon",
  "SYP": "Syrian Pound",
  "SZL": "Lilangeni",
  "THB": "Baht",
  "TJS": "Somoni",
  "TMT": "Turkmenistan New Manat",
  "TND": "Tunisian Dinar",
  "TOP": "Pa’anga",
  "TRY": "Turkish Lira",
  "TTD": "Trinidad and Tobago Dollar",
  "TWD": "New Taiwan Dollar",
  "TZS": "Tanzanian Shilling",
  "UAH": "Hryvnia",
  "UGX": "Uganda Shilling",
  "USD": "US Dollar",
  "USN": "US Dollar (Next day)",
  "UYI": "Uruguay Peso en Unidades Indexadas (UI)",
  "UYU": "Peso Uruguayo",
  "UYW": "Unidad Previsional",
  "UZS": "Uzbekistan Sum",
  "VED": "Bolívar Soberano",
  "VES": "Bolívar Soberano",
  "VND": "Dong",
  "VUV": "Vatu",
  "WST": "Tala",
  "XAF": "CFA Franc BEAC",
  "XAG": "Silver",
  "XAU": "Gold",
  "XBA": "Bond Markets Unit European Composite Unit (EURCO)",
  "XBB": "Bond Markets Unit European Monetary Unit (E.M.U.-6)",
  "XBC": "Bond Markets Unit European Unit of Account 9 (E.U.A.-9)",
  "XBD": "Bond Markets Unit European Unit of Account 17 (E.U.A.-17)",
  "XCD": "East Caribbean Dollar",
  "XDR": "SDR (Special Drawing Right)",
  "XOF": "CFA Franc BCEAO",
  "XPD": "Palladium",
  "XPF": "CFP Franc",
  "XPT": "Platinum",
  "XSU": "Sucre",
  "XTS": "Codes specifically reserved for testing purposes",
  "XUA": "ADB Unit of Account",
  "XXX": "The codes assigned for transactions where no currency is involved",
  "YER": "Yemeni Rial",
  "ZAR": "Rand",
  "ZMW": "Zambian Kwacha",
  "ZWG": "Zimbabwe Gold"
};

export const ISO4217_DEFAULT_SYMBOLS: Readonly<Partial<Record<string, string>>> = {
  "USD": "$",
  "EUR": "€",
  "GBP": "£",
  "JPY": "¥",
  "BRL": "R$",
  "CHF": "CHF",
  "CAD": "CA$",
  "AUD": "A$",
  "CNY": "¥",
  "INR": "₹",
  "KRW": "₩",
  "MXN": "MX$",
  "RUB": "₽",
  "TRY": "₺",
  "PLN": "zł",
  "SEK": "kr",
  "NOK": "kr",
  "DKK": "kr",
  "ZAR": "R",
  "ARS": "AR$",
  "CLP": "CL$",
  "COP": "COL$",
  "PEN": "S/",
  "UYU": "$U",
  "HKD": "HK$",
  "SGD": "S$",
  "NZD": "NZ$",
  "THB": "฿",
  "ILS": "₪",
  "PHP": "₱",
  "CZK": "Kč",
  "HUF": "Ft"
};

export function normalizeIso4217Numeric(value: string): string | null {
  const digits = value.replace(/\D/g, "");
  if (!/^\d{1,3}$/.test(digits)) return null;
  return digits.padStart(3, "0");
}

export function lookupIso4217Alpha(numericCode: string): string | null {
  const normalized = normalizeIso4217Numeric(numericCode);
  if (!normalized) return null;
  return ISO4217_NUMERIC_TO_ALPHA[normalized] ?? null;
}
